---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  info_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    when: D
    filename: ./logs/info.log
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    when: D
    filename: ./logs/errors.log
    backupCount: 20
    encoding: utf8

root:
  level: INFO
  handlers: [info_file_handler, error_file_handler]
...
